# config.yaml

pandoc_options:
  from: "markdown+footnotes+mark"
  table_style: "Light Shading"

styles:
  - custom_name: "IBM Title"
    base_name: "Title"
    font_size: 28
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 12

  - custom_name: "IBM Subtitle"
    base_name: "Subtitle"
    font_size: 14
    bold: false
    italic: true
    font_color: [50, 50, 50]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Normal"
    base_name: "Normal"
    font_size: 11
    bold: false
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 0

  - custom_name: "IBM Heading 1"
    base_name: "Heading 1"
    font_size: 24
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 8

  - custom_name: "IBM Heading 2"
    base_name: "Heading 2"
    font_size: 18
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Heading 3"
    base_name: "Heading 3"
    font_size: 14
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Heading 4"
    base_name: "Heading 4"
    font_size: 12
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Heading 5"
    base_name: "Heading 5"
    font_size: 10
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Heading 6"
    base_name: "Heading 6"
    font_size: 10
    bold: true
    italic: false
    font_color: [0, 0, 0]
    space_before: 0
    space_after: 6

  - custom_name: "IBM Quote"
    base_name: "Quote"
    font_size: 11
    bold: false
    italic: true
    font_color: [60, 60, 60]
    space_before: 6
    space_after: 6
